config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :accounts, only: [:show, :new, :create] do
    resources :transactions, only: [:new, :create]
  end

  root to: "accounts#show"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions_from, class_name: 'Transaction', foreign_key: :account_from_id
  has_many :transactions_to, class_name: 'Transaction', foreign_key: :account_to_id

  validates :balance, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def transfer_amount(params)
    params_amount = params.dig('transaction', 'amount').to_i
    return false if balance < params_amount

    user = User.find_by(id: params[:user])
    account_to = user.account

    return false if account_to.nil?

    update(balance: balance - params_amount)
    account_to.update(balance: account_to.balance + params_amount)
    transactions_from.create!(account_to_id: account_to.id, amount: params_amount)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account_from, class_name: 'Account', foreign_key: :account_from_id, optional: true
  belongs_to :account_to, class_name: 'Account', foreign_key: :account_to_id, optional: true

  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :account, dependent: :destroy

  scope :all_with_valid_accounts_except, -> (user) { joins(:account).where.not(id: user) }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end

  def new
    @account = current_user.build_account
  end

  def create
    @account = current_user.build_account(account_params)

    redirect_to root_path if @account.save
  end

  def show
    @account = current_user.account
    @transactions_from = @account&.transactions_from
    @transactions_to = @account&.transactions_to
  end

  private

  def account_params
    params.require(:account).permit(:balance)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_account

  def index; end

  def new
    @transaction = Transaction.new
    @users = User.all_with_valid_accounts_except(current_user)
  end

  def create
    @account.transfer_amount(params)

    redirect_to root_path
  end

  private

  def set_account
    @account = Account.find_by(id: params[:account_id])
  end

  def set_user_account
    @user = User.find_by(id: params[:user])
    @account_to = @user.account
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/new.html.erb
<%= form_for @account, url: accounts_path, method: :post do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :balance, "Balance:", class: 'form-control', min: '1' %>
      <%= f.number_field :balance, class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>

app/views/accounts/show.html.erb
<h1>Account Details</h1>

<p>Balance: <%= @account.balance %></p>

<% if @account.present? %>
  <%= link_to 'Transfer Money', new_account_transaction_path(@account) %>
<% else %>
  <%= link_to 'Create Account', new_account_path(current_user) %>
<% end %>

<h3>Credits Sent</h3>

<% @transactions_from&.each do |transaction| %>
  <p>Amount: <%= transaction.amount %></p>
  <p>To: <%= transaction.account_to&.user&.email %></p>
<% end %>

<h3>Credits Received</h3>

<% @transactions_to&.each do |transaction| %>
  <p>Amount: <%= transaction.amount %></p>
  <p>From: <%= transaction.account_from&.user&.email %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BankingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/transactions/new.html.erb
<%= form_for @transaction, url: account_transactions_path(@account), method: :post do |f| %>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :amount, "Amount:", class: 'form-control' %>
      <%= f.number_field :amount, class: 'form-control', min: '1' %>
    </div>
    <div class="col-md-6">
      <label>Users: </label>
      <%= select_tag :user, options_from_collection_for_select(@users, 'id', 'email'), prompt: 'Select User', class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Submit', class: 'btn btn-secondary' %>
<% end %>